services:
  app:
    build: .
    container_name: image_extractor_app
    restart: unless-stopped
    ports:
      - "${PORT:-8005}:${PORT:-8005}"
    environment:
      - PORT=${PORT:-8005}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - MONGODB_URL=${MONGODB_URL}
      - LANGSMITH_TRACING=${LANGSMITH_TRACING}
      - LANGSMITH_ENDPOINT=${LANGSMITH_ENDPOINT}
      - LANGSMITH_PROJECT=${LANGSMITH_PROJECT}
      - LANGSMITH_API_KEY=${LANGSMITH_API_KEY}
    networks:
      - citi-intern-network

  mongodb:
    image: mongo:latest
    container_name: image_extractor_mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: image_extractor
    volumes:
      - mongodb_data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - citi-intern-network

  mongo-express:
    image: mongo-express:latest
    container_name: image_extractor_mongo_express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password123
      ME_CONFIG_MONGODB_URL: mongodb://admin:password123@mongodb:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin123
    depends_on:
      - mongodb
    networks:
      - citi-intern-network

volumes:
  mongodb_data:

networks:
  citi-intern-network:
    external: true 